###

#
# Pub Sub Service Settings
#

### Integrated Settings (i.e. using chariott's service discovery)

# The URI that the Chariott Service Discovery listens on for requests.
# Example: "http://0.0.0.0:50000"
chariott_uri: "http://0.0.0.0:50000"

# The namespace of the Pub Sub Service.
# Example: "sdv.pubsub"
namespace: "sdv.pubsub"

# The name of the Pub Sub Service.
# Example: "dynamic.pubsub"
name: "dynamic.pubsub"

# The IP address and port number that the Pub Sub Service listens on for requests.
# Example: "0.0.0.0:50051"
pub_sub_authority: "0.0.0.0:50051"

# The URI of the messaging service used to facilitate publish and subscribe functionality.
# Example: "mqtt://0.0.0.0:1883"
messaging_uri: "mqtt://0.0.0.0:1883"

###
